/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import modelo.ResultSetTableModel;

/**
 *
 * @author casas
 */
public class InternalConsultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltas
     */
    public InternalConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoRadios = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BtnBuscar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        CajaSegundoApellido = new javax.swing.JTextField();
        BtnLimpiar = new javax.swing.JButton();
        CajaPrimerApellido = new javax.swing.JTextField();
        SpinnerSemestre = new javax.swing.JSpinner();
        CajaNombres = new javax.swing.JTextField();
        ComboCarrera = new javax.swing.JComboBox<>();
        RadioButtonNombres = new javax.swing.JRadioButton();
        RadioButtonPrimerApellido = new javax.swing.JRadioButton();
        RadioButtonSegundoApellido = new javax.swing.JRadioButton();
        RadioButtonSemestre = new javax.swing.JRadioButton();
        RadioButtonCarrera = new javax.swing.JRadioButton();
        RadioButtonTodos = new javax.swing.JRadioButton();
        RadioButtonEdad = new javax.swing.JRadioButton();
        SpinnerEdad = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(580, 480));
        setMinimumSize(new java.awt.Dimension(580, 480));
        setPreferredSize(new java.awt.Dimension(580, 480));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTAS ALUMNOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num. Control", "Nombres", "Ap. Paterno", "Ap. Materno", "Edad", "Semestre", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        BtnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnBuscar.setText("BUSCAR");
        BtnBuscar.setNextFocusableComponent(BtnLimpiar);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnCancelar.setText("CANCELAR");
        BtnCancelar.setAlignmentY(0.0F);
        BtnCancelar.setNextFocusableComponent(RadioButtonTodos);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        CajaSegundoApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaSegundoApellido.setNextFocusableComponent(RadioButtonEdad);
        CajaSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaSegundoApellidoKeyPressed(evt);
            }
        });

        BtnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnLimpiar.setText("LIMPIAR");
        BtnLimpiar.setAlignmentY(0.0F);
        BtnLimpiar.setNextFocusableComponent(BtnCancelar);
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        CajaPrimerApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaPrimerApellido.setNextFocusableComponent(RadioButtonSegundoApellido);
        CajaPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaPrimerApellidoKeyPressed(evt);
            }
        });

        SpinnerSemestre.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        SpinnerSemestre.setNextFocusableComponent(RadioButtonCarrera);

        CajaNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaNombres.setNextFocusableComponent(RadioButtonPrimerApellido);
        CajaNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaNombresKeyPressed(evt);
            }
        });

        ComboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Carrera ...", "CP", "IA", "IM", "ISC", "LA" }));
        ComboCarrera.setNextFocusableComponent(BtnBuscar);
        ComboCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ComboCarreraKeyPressed(evt);
            }
        });

        GrupoRadios.add(RadioButtonNombres);
        RadioButtonNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonNombres.setText("NOMBRES:");
        RadioButtonNombres.setNextFocusableComponent(CajaNombres);
        RadioButtonNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonNombresActionPerformed(evt);
            }
        });

        GrupoRadios.add(RadioButtonPrimerApellido);
        RadioButtonPrimerApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonPrimerApellido.setText("PRIMER APELLIDO:");
        RadioButtonPrimerApellido.setNextFocusableComponent(CajaPrimerApellido);
        RadioButtonPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonPrimerApellidoActionPerformed(evt);
            }
        });

        GrupoRadios.add(RadioButtonSegundoApellido);
        RadioButtonSegundoApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonSegundoApellido.setText("SEGUNDO APELLIDO:");
        RadioButtonSegundoApellido.setNextFocusableComponent(CajaSegundoApellido);
        RadioButtonSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSegundoApellidoActionPerformed(evt);
            }
        });

        GrupoRadios.add(RadioButtonSemestre);
        RadioButtonSemestre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonSemestre.setText("SEMESTRE:");
        RadioButtonSemestre.setNextFocusableComponent(SpinnerSemestre);
        RadioButtonSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSemestreActionPerformed(evt);
            }
        });

        GrupoRadios.add(RadioButtonCarrera);
        RadioButtonCarrera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonCarrera.setText("CARRERA:");
        RadioButtonCarrera.setNextFocusableComponent(ComboCarrera);
        RadioButtonCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonCarreraActionPerformed(evt);
            }
        });

        GrupoRadios.add(RadioButtonTodos);
        RadioButtonTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonTodos.setText("MOSTRAR TODOS");
        RadioButtonTodos.setNextFocusableComponent(RadioButtonNombres);
        RadioButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonTodosActionPerformed(evt);
            }
        });

        GrupoRadios.add(RadioButtonEdad);
        RadioButtonEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButtonEdad.setText("EDAD:");
        RadioButtonEdad.setNextFocusableComponent(SpinnerEdad);
        RadioButtonEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonEdadActionPerformed(evt);
            }
        });

        SpinnerEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        SpinnerEdad.setNextFocusableComponent(SpinnerSemestre);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RadioButtonTodos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RadioButtonPrimerApellido)
                                    .addComponent(RadioButtonEdad)
                                    .addComponent(RadioButtonSegundoApellido)
                                    .addComponent(RadioButtonSemestre)
                                    .addComponent(RadioButtonNombres)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RadioButtonCarrera)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RadioButtonTodos)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonNombres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajaPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonPrimerApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajaSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonSegundoApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonEdad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioButtonSemestre)
                            .addComponent(SpinnerSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonCarrera)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BtnBuscar)
                        .addGap(44, 44, 44)
                        .addComponent(BtnLimpiar)
                        .addGap(38, 38, 38)
                        .addComponent(BtnCancelar)))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        if(RadioButtonNombres.isSelected()){
            if(!CajaNombres.getText().equals(""))
                actualizarTabla("SELECT * FROM Alumnos WHERE Nombres LIKE '%" + CajaNombres.getText() + "%'");
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        }
        else if(RadioButtonPrimerApellido.isSelected()){
            if(!CajaPrimerApellido.getText().equals(""))
                actualizarTabla("SELECT * FROM Alumnos WHERE Primer_Ap LIKE '%" + CajaPrimerApellido.getText() + "%'");
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        }
        else if(RadioButtonSegundoApellido.isSelected()){
            if(!CajaSegundoApellido.getText().equals(""))
                actualizarTabla("SELECT * FROM Alumnos WHERE Segundo_Ap LIKE '%" + CajaSegundoApellido.getText() + "%'");
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        }
        else if(RadioButtonEdad.isSelected()){
            if((int)SpinnerEdad.getValue() != 0)
                actualizarTabla("SELECT * FROM Alumnos WHERE Edad = " + (byte)(int)SpinnerEdad.getValue());
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        }
        else if(RadioButtonSemestre.isSelected()){
            if((int)SpinnerSemestre.getValue() != 0)
                actualizarTabla("SELECT * FROM Alumnos WHERE Semestre = " + (byte)(int)SpinnerSemestre.getValue());
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        }
        else if(RadioButtonCarrera.isSelected()){
            if(ComboCarrera.getSelectedIndex() != 0)
                actualizarTabla("SELECT * FROM Alumnos WHERE Carrera = '" + ComboCarrera.getSelectedItem().toString() + "'");
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        }
        if(Tabla.getRowCount() == 0){
            limpiarTabla();
            JOptionPane.showMessageDialog(rootPane, "No se encontro ningun registro.");
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void CajaNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaNombresKeyPressed
        if(evt.getKeyCode() == 10)
            juzgarComponente();
    }//GEN-LAST:event_CajaNombresKeyPressed

    private void CajaPrimerApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaPrimerApellidoKeyPressed
        if(evt.getKeyCode() == 10)
            juzgarComponente();
    }//GEN-LAST:event_CajaPrimerApellidoKeyPressed

    private void CajaSegundoApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaSegundoApellidoKeyPressed
        if(evt.getKeyCode() == 10)
            juzgarComponente();
    }//GEN-LAST:event_CajaSegundoApellidoKeyPressed

    private void ComboCarreraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboCarreraKeyPressed
        if(evt.getKeyCode() == 10)
            juzgarComponente();
    }//GEN-LAST:event_ComboCarreraKeyPressed

    private void RadioButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonTodosActionPerformed
        actualizarTabla(MOSTRAR_TODOS_LOS_DATOS);
        habilitarCampos(false, false, false, false, false, false, false);
    }//GEN-LAST:event_RadioButtonTodosActionPerformed

    private void RadioButtonNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonNombresActionPerformed
        habilitarCampos(true, false, false, false, false, false, true);
        limpiarTabla();
    }//GEN-LAST:event_RadioButtonNombresActionPerformed

    private void RadioButtonPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonPrimerApellidoActionPerformed
        habilitarCampos(false, true, false, false, false, false, true);
        limpiarTabla();
    }//GEN-LAST:event_RadioButtonPrimerApellidoActionPerformed

    private void RadioButtonSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSegundoApellidoActionPerformed
        habilitarCampos(false, false, true, false, false, false, true);
        limpiarTabla();
    }//GEN-LAST:event_RadioButtonSegundoApellidoActionPerformed

    private void RadioButtonSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSemestreActionPerformed
        habilitarCampos(false, false, false,false, true, false, true);
        limpiarTabla();
    }//GEN-LAST:event_RadioButtonSemestreActionPerformed

    private void RadioButtonCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonCarreraActionPerformed
        habilitarCampos(false, false, false, false, false, true, true);
        limpiarTabla();
    }//GEN-LAST:event_RadioButtonCarreraActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        establecerComponentesDefault();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void RadioButtonEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonEdadActionPerformed
        habilitarCampos(false, false, false, true, false, false, true);
        limpiarTabla();
    }//GEN-LAST:event_RadioButtonEdadActionPerformed

    public void establecerComponentesDefault(){
        restablecerCompontes(CajaNombres, CajaPrimerApellido, CajaSegundoApellido, SpinnerSemestre, ComboCarrera);
        habilitarCampos(false, false, false, false, false, false, false);
        GrupoRadios.clearSelection();
        limpiarTabla();
    }

    public void habilitarCampos(boolean nom, boolean PAp, boolean sAp, boolean eda, boolean sem, boolean carr, boolean boton){
        CajaNombres.setEnabled(nom);
        CajaNombres.setText("");
        CajaPrimerApellido.setEnabled(PAp);
        CajaPrimerApellido.setText("");
        CajaSegundoApellido.setEnabled(sAp);
        CajaSegundoApellido.setText("");
        SpinnerEdad.setEnabled(eda);
        SpinnerEdad.setValue(0);
        SpinnerSemestre.setEnabled(sem);
        SpinnerSemestre.setValue(0);
        ComboCarrera.setEnabled(carr);
        ComboCarrera.setSelectedIndex(0);
        BtnBuscar.setEnabled(boton);
    }
    
    public void actualizarTabla(String consulta){
        String controlador = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost/Escuela?useTimezone=true&serverTimezone=UTC";
        ResultSetTableModel modeloDatos = null;

        try {
            modeloDatos = new ResultSetTableModel(controlador, url, consulta);
        } catch (ClassNotFoundException | SQLException e) {}

        Tabla.setModel(modeloDatos);
    }
    
    public void restablecerCompontes(JComponent...componentes){
        for(JComponent c : componentes){
            if(c instanceof JTextField)
                ((JTextField) c).setText("");
            if(c instanceof JComboBox)
                ((JComboBox<?>) c).setSelectedIndex(0);
            if(c instanceof JSpinner)
                ((JSpinner) c).setValue(0);
        }		
    }
    
    public void juzgarComponente(){
        if(RadioButtonNombres.isSelected())
            if(!CajaNombres.getText().equals(""))
                BtnBuscar.doClick();
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        else if(RadioButtonPrimerApellido.isSelected())
            if(!CajaPrimerApellido.getText().equals(""))
                BtnBuscar.doClick();
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        else if(RadioButtonSegundoApellido.isSelected())
            if(!CajaSegundoApellido.getText().equals(""))
                BtnBuscar.doClick();
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        else if(RadioButtonEdad.isSelected())
            if((int)SpinnerEdad.getValue() != 0)
                BtnBuscar.doClick();
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        else if(RadioButtonSemestre.isSelected())
            if((int)SpinnerSemestre.getValue() != 0)
                BtnBuscar.doClick();
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
        else if(RadioButtonCarrera.isSelected())
            if(ComboCarrera.getSelectedIndex() != 0)
                BtnBuscar.doClick();
            else
                JOptionPane.showMessageDialog(rootPane, "El campo esta vacio.");
    }
    
    public void limpiarTabla(){
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num_Control", "Nombres", "Primer_Ap", "Segundo_Ap", "Edad", "Semestre", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JTextField CajaNombres;
    private javax.swing.JTextField CajaPrimerApellido;
    private javax.swing.JTextField CajaSegundoApellido;
    private javax.swing.JComboBox<String> ComboCarrera;
    private javax.swing.ButtonGroup GrupoRadios;
    private javax.swing.JRadioButton RadioButtonCarrera;
    private javax.swing.JRadioButton RadioButtonEdad;
    private javax.swing.JRadioButton RadioButtonNombres;
    private javax.swing.JRadioButton RadioButtonPrimerApellido;
    private javax.swing.JRadioButton RadioButtonSegundoApellido;
    private javax.swing.JRadioButton RadioButtonSemestre;
    private javax.swing.JRadioButton RadioButtonTodos;
    private javax.swing.JSpinner SpinnerEdad;
    private javax.swing.JSpinner SpinnerSemestre;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    final static String MOSTRAR_TODOS_LOS_DATOS = "SELECT * FROM Alumnos";
}