/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AlumnoDAO;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import modelo.Alumno;
import modelo.ResultSetTableModel;

/**
 *
 * @author casas
 */
public class InternalAltas extends javax.swing.JInternalFrame {

    /**
     * Creates new form altas
     */
    public InternalAltas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CajaNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CajaNumeroControl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComboCarrera = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CajaSegundoApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CajaPrimerApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SpinnerEdad = new javax.swing.JSpinner();
        SpinnerSemestre = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(580, 480));
        setMinimumSize(new java.awt.Dimension(580, 480));
        setPreferredSize(new java.awt.Dimension(580, 480));

        CajaNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaNombres.setNextFocusableComponent(CajaPrimerApellido);
        CajaNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaNombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaNombresKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NOMBRES:");

        CajaNumeroControl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaNumeroControl.setNextFocusableComponent(CajaNombres);
        CajaNumeroControl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaNumeroControlKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaNumeroControlKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NÚMERO DE CONTROL:");

        BtnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAgregar.setText("AGREGAR");
        BtnAgregar.setNextFocusableComponent(BtnLimpiar);
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnLimpiar.setText("LIMPIAR");
        BtnLimpiar.setNextFocusableComponent(BtnCancelar);
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnCancelar.setText("CANCELAR");
        BtnCancelar.setNextFocusableComponent(CajaNumeroControl);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num. Control", "Nombres", "Ap. Paterno", "Ap. Materno", "Edad", "Semestre", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTAS ALUMNOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ComboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Carrera ...", "CP", "IA", "IM", "ISC", "LA" }));
        ComboCarrera.setNextFocusableComponent(BtnAgregar);
        ComboCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ComboCarreraKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CARRERA:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("SEMESTRE:");

        CajaSegundoApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaSegundoApellido.setNextFocusableComponent(SpinnerEdad);
        CajaSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaSegundoApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaSegundoApellidoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SEGUNDO APELLIDO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("PRIMER APELLIDO:");

        CajaPrimerApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CajaPrimerApellido.setNextFocusableComponent(CajaSegundoApellido);
        CajaPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaPrimerApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaPrimerApellidoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("EDAD:");

        SpinnerEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        SpinnerEdad.setNextFocusableComponent(SpinnerSemestre);
        SpinnerEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SpinnerEdadKeyPressed(evt);
            }
        });

        SpinnerSemestre.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        SpinnerSemestre.setNextFocusableComponent(ComboCarrera);
        SpinnerSemestre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SpinnerSemestreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajaNumeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CajaPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CajaSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(ComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(SpinnerSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCancelar)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaNumeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BtnAgregar))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BtnLimpiar))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SpinnerSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if(verificarEstadoComponentes()){
            String numControl = "";
            switch (ComboCarrera.getSelectedItem().toString()) {
                case "CP":
                    numControl = "C"+CajaNumeroControl.getText();
                    break;
                case "IA":
                    numControl = "I"+CajaNumeroControl.getText();
                    break;
                case "IM":
                    numControl = "M"+CajaNumeroControl.getText();
                    break;
                case "ISC":
                    numControl = "S"+CajaNumeroControl.getText();
                    break;
                case "LA":
                    numControl = "A"+CajaNumeroControl.getText();
                    break;
            } 
            alumno = new Alumno(numControl, CajaNombres.getText(), CajaPrimerApellido.getText(), CajaSegundoApellido.getText(), (byte)(int)SpinnerEdad.getValue(), (byte)(int)SpinnerSemestre.getValue(), ComboCarrera.getSelectedItem().toString());
            
            Alumno al = ALUMNO_DAO.buscarAlumno(numControl);
            if(al == null)
                if(CajaNumeroControl.getText().length() == 8)
                    if(ALUMNO_DAO.agregarAlumno(alumno)){
                        JOptionPane.showMessageDialog(rootPane, "Alumno agregado correctamente.");
                        establecerComponentesDefault();
                    }
                    else
                        JOptionPane.showMessageDialog(rootPane, "Error al agregar el alumno.");
                else
                    JOptionPane.showMessageDialog(rootPane, "El formato de Numero de Control debe incluir 8 digitos.");
            else
                JOptionPane.showMessageDialog(rootPane, "El numero de control ingresado ya existe.");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Aun existen campos vacios.");
        actualizarTabla(MOSTRAR_TODOS_LOS_REGISTROS);
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        establecerComponentesDefault();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void CajaNumeroControlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaNumeroControlKeyPressed
        if(evt.getKeyCode() == 10)
            BtnAgregar.doClick();
        
    }//GEN-LAST:event_CajaNumeroControlKeyPressed

    private void CajaNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaNombresKeyPressed
        if(evt.getKeyCode() == 10)
            BtnAgregar.doClick();
    }//GEN-LAST:event_CajaNombresKeyPressed

    private void CajaPrimerApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaPrimerApellidoKeyPressed
        if(evt.getKeyCode() == 10)
            BtnAgregar.doClick();
    }//GEN-LAST:event_CajaPrimerApellidoKeyPressed

    private void CajaSegundoApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaSegundoApellidoKeyPressed
        if(evt.getKeyCode() == 10)
            BtnAgregar.doClick();
    }//GEN-LAST:event_CajaSegundoApellidoKeyPressed

    private void ComboCarreraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboCarreraKeyPressed
        if(evt.getKeyCode() == 10)
            BtnAgregar.doClick();
    }//GEN-LAST:event_ComboCarreraKeyPressed

    private void CajaNumeroControlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaNumeroControlKeyTyped
        verificarEntradaNumControl(CajaNumeroControl, evt);
    }//GEN-LAST:event_CajaNumeroControlKeyTyped

    private void CajaNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaNombresKeyTyped
        verificarEntradaTexto(CajaNombres, evt);
    }//GEN-LAST:event_CajaNombresKeyTyped

    private void CajaPrimerApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaPrimerApellidoKeyTyped
        verificarEntradaTexto(CajaPrimerApellido, evt);
    }//GEN-LAST:event_CajaPrimerApellidoKeyTyped

    private void CajaSegundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaSegundoApellidoKeyTyped
        verificarEntradaTexto(CajaSegundoApellido, evt);
    }//GEN-LAST:event_CajaSegundoApellidoKeyTyped

    private void SpinnerEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SpinnerEdadKeyPressed
        if(evt.getKeyCode() == 10)
            BtnAgregar.doClick();
    }//GEN-LAST:event_SpinnerEdadKeyPressed

    private void SpinnerSemestreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SpinnerSemestreKeyPressed
        if(evt.getKeyCode() == 10)
            BtnAgregar.doClick();
    }//GEN-LAST:event_SpinnerSemestreKeyPressed

    public void establecerComponentesDefault(){
        restablecerCompontes(CajaNumeroControl, CajaNombres, CajaPrimerApellido, CajaSegundoApellido, SpinnerEdad, SpinnerSemestre, ComboCarrera);
    }
    
    public boolean verificarEstadoComponentes(){
        boolean bandera=true;

        if(CajaNumeroControl.getText().equals(""))
            bandera=false;
        if(CajaNombres.getText().equals(""))
            bandera=false;
        if(CajaPrimerApellido.getText().equals(""))
            bandera=false;
        if(CajaSegundoApellido.getText().equals(""))
            bandera=false;
        if((int)SpinnerEdad.getValue() == 0)
            bandera=false;
        if((int)SpinnerSemestre.getValue() == 0)
            bandera=false;
        if(ComboCarrera.getSelectedIndex() == 0)
            bandera=false;

        return bandera;
    }
    
    public void actualizarTabla(String consulta){
        String controlador = "com.mysql.cj.jdbc.Driver";
        String url = "jdbc:mysql://localhost/Escuela?useTimezone=true&serverTimezone=UTC";
        ResultSetTableModel modeloDatos =  null;

        try {
            modeloDatos = new ResultSetTableModel(controlador, url, consulta);
        } catch (ClassNotFoundException | SQLException e) {}

        Tabla.setModel(modeloDatos);
    }
    
    public void restablecerCompontes(JComponent...componentes){
        for(JComponent c : componentes){
            if(c instanceof JTextField)
                ((JTextField) c).setText("");
            if(c instanceof JComboBox)
                ((JComboBox<?>) c).setSelectedIndex(0);
            if(c instanceof JSpinner)
                ((JSpinner) c).setValue(0);
        }		
    }

    public void verificarEntradaNumControl(JTextField txtF, KeyEvent e){
        if (txtF.getText().length() == 8) 
            e.consume();			
        else
            if(!Character.isDigit(e.getKeyChar()))
                e.consume();
    }
    
    public void verificarEntradaTexto(JTextField txtF, KeyEvent e){
        if (txtF.getText().length() == 50) 
            e.consume();			
        else
            if(Character.isDigit(e.getKeyChar()))
                e.consume();
            else
                if(!Character.isLetter(e.getKeyChar()) && e.getKeyChar()!=KeyEvent.VK_SPACE && e.getKeyChar()!=KeyEvent.VK_PERIOD)
                    e.consume();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JTextField CajaNombres;
    private javax.swing.JTextField CajaNumeroControl;
    private javax.swing.JTextField CajaPrimerApellido;
    private javax.swing.JTextField CajaSegundoApellido;
    private javax.swing.JComboBox<String> ComboCarrera;
    private javax.swing.JSpinner SpinnerEdad;
    private javax.swing.JSpinner SpinnerSemestre;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    final static String MOSTRAR_TODOS_LOS_REGISTROS = "SELECT * FROM Alumnos";
    Alumno alumno;
    final static AlumnoDAO ALUMNO_DAO = new AlumnoDAO();
}