/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author casas
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        agregarInternals();
        this.setLocationRelativeTo(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        MenuAlumnos = new javax.swing.JMenu();
        MenuItemAltas = new javax.swing.JMenuItem();
        MenuItemBajas = new javax.swing.JMenuItem();
        MenuItemModificaciones = new javax.swing.JMenuItem();
        MenuItemConsultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(585, 530));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(580, 480));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(580, 480));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MenuAlumnos.setText("Alumnos");

        MenuItemAltas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemAltas.setText("Alta Alumnos");
        MenuItemAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAltasActionPerformed(evt);
            }
        });
        MenuAlumnos.add(MenuItemAltas);

        MenuItemBajas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemBajas.setText("Baja Alumnos");
        MenuItemBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBajasActionPerformed(evt);
            }
        });
        MenuAlumnos.add(MenuItemBajas);

        MenuItemModificaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemModificaciones.setText("Modificar Alumnos");
        MenuItemModificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModificacionesActionPerformed(evt);
            }
        });
        MenuAlumnos.add(MenuItemModificaciones);

        MenuItemConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemConsultas.setText("Consultar Alumnos");
        MenuItemConsultas.setIconTextGap(0);
        MenuItemConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemConsultasActionPerformed(evt);
            }
        });
        MenuAlumnos.add(MenuItemConsultas);

        Menu.add(MenuAlumnos);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void MenuItemAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAltasActionPerformed
        altas.setVisible(true);
        altas.establecerComponentesDefault();
        altas.actualizarTabla(MOSTRARTODOSLOSDATOS);
        bajas.setVisible(false);
        modificaciones.setVisible(false);
        consultas.setVisible(false);
    }//GEN-LAST:event_MenuItemAltasActionPerformed

    private void MenuItemBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBajasActionPerformed
        altas.setVisible(false);
        bajas.setVisible(true);
        bajas.establecerComponentesDefault();
        bajas.actualizarTabla(MOSTRARTODOSLOSDATOS);
        modificaciones.setVisible(false);
        consultas.setVisible(false);
    }//GEN-LAST:event_MenuItemBajasActionPerformed

    private void MenuItemModificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModificacionesActionPerformed
        altas.setVisible(false);
        bajas.setVisible(false);
        modificaciones.setVisible(true);
        modificaciones.establecerComponentesDefault();
        modificaciones.actualizarTabla(MOSTRARTODOSLOSDATOS);
        consultas.setVisible(false);
    }//GEN-LAST:event_MenuItemModificacionesActionPerformed

    private void MenuItemConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemConsultasActionPerformed
        altas.setVisible(false);
        bajas.setVisible(false);
        modificaciones.setVisible(false);
        consultas.setVisible(true);
        consultas.establecerComponentesDefault();
        consultas.limpiarTabla();
    }//GEN-LAST:event_MenuItemConsultasActionPerformed

    public final void agregarInternals() {
        jDesktopPane1.add(altas);
        jDesktopPane1.add(bajas);
        jDesktopPane1.add(modificaciones);
        jDesktopPane1.add(consultas);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuAlumnos;
    private javax.swing.JMenuItem MenuItemAltas;
    private javax.swing.JMenuItem MenuItemBajas;
    private javax.swing.JMenuItem MenuItemConsultas;
    private javax.swing.JMenuItem MenuItemModificaciones;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
    InternalAltas altas = new InternalAltas();
    InternalBajas bajas = new InternalBajas();
    InternalModificaciones modificaciones = new InternalModificaciones();
    InternalConsultas consultas = new InternalConsultas();
    final static String MOSTRARTODOSLOSDATOS = "SELECT * FROM Alumnos";
}